### PR TITLE
Post and Like structure revist

### LINKED ISSUE #39: Avoid double liking
**Describe the bug**
Currently when storing the like of a user to a post, we do not check if the user has already liked the post itself. This leads to the possibility of double-liking. 

**To Reproduce**
1. Create a post
2. Like the post 
3. Like the post again

**Expected behavior**
An error should be returned when trying to like the post twice.

### PR DESCRIPTION
**Pull request by RiccardoM**
## Description
This PR implements various `Post` and `Like` structure improvements. 
Also, the various messages have been revisited in order to delete useless time fields. 
Tests have been added and documentation has been written.

Closes #39 

## Checklist
- [x] Targeted PR against correct branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Wrote tests
- [x] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Comment by kwunyeung** [comment]
Let's target merging it this weekend and launch testnet.

File: x/magpie/internal/keeper/handler.go [hunk 1]
```diff
@@ -82,7 +82,13 @@ func handleMsgCreateSession(ctx sdk.Context, keeper Keeper, msg types.MsgCreateS
 		Signature:     msg.Signature,
 	}
 
-	if err := keeper.CreateSession(ctx, session); err != nil {
+	// Check for any previously existing session
+	if _, found := keeper.GetSession(ctx, session.SessionID); found {
+		return sdk.ErrUnknownRequest(fmt.Sprintf("Session with id %s already exists", session.SessionID)).Result()
```
Comment (kwunyeung) [inline x/magpie/internal/keeper/handler.go]: Not a big deal but looks strange if a function is named `GetSession` where the function is to check whether the session exists.

File: x/posts/internal/keeper/keeper.go [hunk 2]
```diff
@@ -104,84 +88,42 @@ func (k Keeper) GetPosts(ctx sdk.Context) []types.Post {
...
-	like.PostID = post.PostID
+	// Get the existent likes
+	var likes types.Likes
+	k.Cdc.MustUnmarshalBinaryBare(store.Get(key), &likes)
 
-	// Store the like and update the last like id
-	if err := k.SaveLike(ctx, like); err != nil {
-		return err
+	// Check for double likes
+	if likes.ContainsOwnerLike(like.Owner) {
```
Comment (kwunyeung) [inline x/posts/internal/keeper/keeper.go]: Can this be done in `ValidateBasic()` or `ValidateBasic()` can't access this data?

Comment (kwunyeung) [inline x/posts/internal/keeper/keeper.go]: Possible to query the state before broadcasting the message?

Comment (RiccardoM) [reply x/posts/internal/keeper/keeper.go]: Unluckily, not. The `ValidateBasic` method has no access to the state.

On the other hand, we can move this to the handler. Do you think it would be better?

File: x/magpie/internal/keeper/handler.go (hunk 1 above)
Comment (RiccardoM) [reply x/magpie/internal/keeper/handler.go]: The `GetSession` here is used to check if a session already exists, but elsewhere (i.e inside the `querier`) the same method is used to get a session using its ID.

Here we use the second returned value, which allows for faster and easier comparison than the first one. It's just a convinient way to keep the code DRY and avoiding having multiple methods with very similar functionality
