### PR TITLE
Empty message with media implementation

### LINKED ISSUE #110: Cannot create an empty-message post with a photo
## Bug description
Currently it's not possible to create a post with an empty message but containing an image.

## Steps to reproduce
Create a post with an empty message but a photo. An error will be returned. 

## Expected behavior
The post is created properly.

### PR DESCRIPTION
**Pull request by bragaz**
## Description
This PR added the possibility to post an empty message with medias without errors.
Closes #110 

## Checklist
- [x] Targeted PR against correct branch.
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Wrote unit tests.
- [x] Wrote integration tests (simulation & CLI). 
- [x] Updated the documentation. 
- [x] Added an entry to the `CHANGELOG.md` file.
- [x] Re-reviewed `Files changed` in the Github PR explorer.

### CODE REVIEW

File: x/posts/internal/types/msgs.go [hunk 1]
```diff
@@ -56,7 +56,7 @@ func (msg MsgCreatePost) ValidateBasic() error {
 		return sdkerrors.Wrap(sdkerrors.ErrInvalidAddress, fmt.Sprintf("Invalid creator address: %s", msg.Creator))
 	}
 
-	if len(strings.TrimSpace(msg.Message)) == 0 {
+	if len(strings.TrimSpace(msg.Message)) == 0 && len(msg.Medias) == 0 {
 		return sdkerrors.Wrap(sdkerrors.ErrInvalidRequest, "Post message cannot be empty nor blank")
```
Comment (RiccardoM) [inline x/posts/internal/types/msgs.go]: Probably we want to change this error message as well now

File: x/posts/internal/types/msgs_test.go [hunk 2]
```diff
@@ -75,7 +75,7 @@ func TestMsgCreatePost_ValidateBasic(t *testing.T) {
 			error: sdkerrors.Wrap(sdkerrors.ErrInvalidAddress, "Invalid creator address: "),
 		},
 		{
-			name: "Empty message returns error",
+			name: "Empty message returns error if medias are empty",
```
Comment (RiccardoM) [inline x/posts/internal/types/msgs_test.go]: I'm not a big fan of editing already existing test cases in this way. We should instead add newer ones that test with: 

- empty message, empty medias
- empty message, non empty medias
- non empty message, empty medias
- non empty message, non empty medias

File: cli_test/cli_posts_test.go [hunk 3]
```diff
@@ -78,7 +78,7 @@ func TestDesmosCLIPostsCreateWithMedias(t *testing.T) {
 
 	// Later usage variables
 	subspace := "4e188d9c17150037d5199bbdb91ae1eb2a78a15aca04cb35530cccb81494b36e"
-	message := "message"
+	message := ""
```
Comment (RiccardoM) [inline cli_test/cli_posts_test.go]: This should not be done. Instead, a new case should be added. We need to test all cases, not just one of them: 

- empty medias, non-empty message
- non-empty medias, non-empty message
- non-empty medias, empty message

File: x/posts/internal/types/msgs.go [hunk 4]
```diff
@@ -56,7 +56,7 @@ func (msg MsgCreatePost) ValidateBasic() error {
 		return sdkerrors.Wrap(sdkerrors.ErrInvalidAddress, fmt.Sprintf("Invalid creator address: %s", msg.Creator))
 	}
 
-	if len(strings.TrimSpace(msg.Message)) == 0 {
+	if len(strings.TrimSpace(msg.Message)) == 0 && len(msg.Medias) == 0 {
```
Comment (RiccardoM) [inline x/posts/internal/types/msgs.go]: I think this check should also be added inside `Post.Validate()` as well

File: x/posts/internal/types/msgs.go [hunk 5]
```diff
@@ -56,8 +56,8 @@ func (msg MsgCreatePost) ValidateBasic() error {
 		return sdkerrors.Wrap(sdkerrors.ErrInvalidAddress, fmt.Sprintf("Invalid creator address: %s", msg.Creator))
 	}
 
-	if len(strings.TrimSpace(msg.Message)) == 0 {
-		return sdkerrors.Wrap(sdkerrors.ErrInvalidRequest, "Post message cannot be empty nor blank")
+	if len(strings.TrimSpace(msg.Message)) == 0 && len(msg.Medias) == 0 {
+		return sdkerrors.Wrap(sdkerrors.ErrInvalidRequest, "Post message cannot be empty nor blank when there are no medias")
```
Comment (RiccardoM) [inline x/posts/internal/types/msgs.go]: I think we can change this to make it more clear

```suggestion
		return sdkerrors.Wrap(sdkerrors.ErrInvalidRequest, "Post message or medias are required and cannot be both blank or empty")
```

File: x/posts/internal/types/msgs_test.go [hunk 6]
```diff
@@ -84,10 +84,55 @@ func TestMsgCreatePost_ValidateBasic(t *testing.T) {
 				map[string]string{},
 				creator,
 				date,
+				nil,
+				msgCreatePost.PollData,
+			),
+			error: sdkerrors.Wrap(sdkerrors.ErrInvalidRequest, "Post message cannot be empty nor blank when there are no medias"),
+		},
+		{
+			name: "Non-empty message returns nil if medias are empty",
```
Comment (RiccardoM) [inline x/posts/internal/types/msgs_test.go]:
```suggestion
			name: "Non-empty message returns no error if medias are empty",
```

File: x/posts/internal/types/msgs_test.go [hunk 7]
```diff
@@ -84,10 +84,55 @@ func TestMsgCreatePost_ValidateBasic(t *testing.T) {
...
+				map[string]string{},
+				creator,
+				date,
+				nil,
+				msgCreatePost.PollData,
+			),
+			error: nil,
+		},
+		{
+			name: "Non-empty message returns nil if medias aren't empty",
```
Comment (RiccardoM) [inline x/posts/internal/types/msgs_test.go]:
```suggestion
			name: "Non-empty message returns no error if medias aren't empty",
```

File: x/posts/internal/types/msgs_test.go [hunk 8]
```diff
@@ -84,10 +84,55 @@ func TestMsgCreatePost_ValidateBasic(t *testing.T) {
...
+				creator,
+				date,
 				msgCreatePost.Medias,
 				msgCreatePost.PollData,
 			),
-			error: sdkerrors.Wrap(sdkerrors.ErrInvalidRequest, "Post message cannot be empty nor blank"),
+			error: nil,
+		},
+		{
+			name: "Empty message returns nil if medias aren't empty",
```
Comment (RiccardoM) [inline x/posts/internal/types/msgs_test.go]:
```suggestion
			name: "Empty message returns no error if medias aren't empty",
```

File: x/posts/internal/types/post.go [hunk 9]
```diff
@@ -170,8 +170,8 @@ func (p Post) Validate() error {
 		return fmt.Errorf("invalid post owner: %s", p.Creator)
 	}
 
-	if len(strings.TrimSpace(p.Message)) == 0 {
-		return fmt.Errorf("post message must be non empty and non blank")
+	if len(strings.TrimSpace(p.Message)) == 0 && len(p.Medias) == 0 {
+		return fmt.Errorf("post message cannot be empty nor blank when there are no medias")
```
Comment (RiccardoM) [inline x/posts/internal/types/post.go]: Can change this to make it more generic

```suggestion
		return fmt.Errorf("post message or medias required, they cannot be both empty")
```
