### PR TITLE
Fix Last Post ID Bug

### LINKED ISSUE #64: Some new posts can't be created with the same invalid error message
These txs are all failed and have error message with the same `Post ID` 17.

`828D4A5EE5488F1B1C67CC72410B2F62CEF7A67DFB4F6EF2CE1FA550136DCDF0`
`4951F960C4A8D222175D377138D1B9519A79FC609E6410B03C71361067FF4BEC`
`6FB74064F5038995FB1DF9FFA246C96B1AF5A5D3DD4A1F452DC5AA299C877809`
`CAEB1E82282EE31F5CAE3D3E99838DBD62064142C90C480CF29976917A88742E`
` D262923277A6FD586A40289E3BFB7D5067FAE1335A9B6652B1CF5B8A8A77C9C2`

Their error messages are all

```
"{\"codespace\":\"sdk\",\"code\":6,\"message\":\"Post with id 17 already exists\"}"
```

### PR DESCRIPTION
**Pull request by bragaz**
## Description
This PR fixes #64  issue where the saving of edited posts broke the `LastPostID` and made impossibile to create new ones.

## Checklist
- [x] Targeted PR against correct branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Wrote tests
- [x] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

File: x/posts/internal/keeper/keeper.go [hunk 1]
```diff
@@ -53,7 +53,9 @@ func (k Keeper) SavePost(ctx sdk.Context, post types.Post) {
 	store.Set([]byte(types.PostStorePrefix+post.PostID.String()), k.Cdc.MustMarshalBinaryBare(&post))
 
 	// Set the last post id
-	store.Set([]byte(types.LastPostIDStoreKey), k.Cdc.MustMarshalBinaryBare(&post.PostID))
+	if post.LastEdited.IsZero() {
```
Comment (RiccardoM) [inline x/posts/internal/keeper/keeper.go]: Although this is a good check, I personally don't think it's the best one. 

One case that might be raise is the following: 

- Post with ID 1 is created
- Post with ID 2 is created
- (Somehow) Post with ID 1 is created again

As they are all created, 1 will be again set as the last ID which should not. 

I think there's a better check which is to check whether the ID of the post that is being saved is greater than the last ID saved. If it is, the last ID will be set. Otherwise it will not be set.

Comment (bragaz) [reply x/posts/internal/keeper/keeper.go]: It make sense, i'll edit it now

**Comment by bragaz** [comment]
I don't understand the last check on the checklist...should i mark files as viewed or not? Or just take a look at them?

**Comment by RiccardoM** [comment]
> I don't understand the last check on the checklist...should i mark files as viewed or not? Or just take a look at them?

It's there to suggest you to look at them to make sure there are no other files that are wrongly included in the PR. It's just an additional safety check to avoid unwanted changes to be merge by error

File: x/posts/internal/keeper/keeper_test.go [hunk 2]
```diff
@@ -75,6 +78,16 @@ func TestKeeper_SavePost(t *testing.T) {
 			},
 			newPost:              types.NewPost(types.PostID(15), types.PostID(1), "Comment", false, "", 0, testPostOwner),
 			expParentCommentsIDs: []types.PostID{types.PostID(15)},
+			expLastID:            types.PostID(15),
+		},
+		{
+			name: "Post with ID greater ID than Last ID stored",
```
Comment (RiccardoM) [inline x/posts/internal/keeper/keeper_test.go]: Perfect. 

Can we have another test case where we save a Post that has in ID that is **not** greater than the last one? This should check that the last one stays the greater one without being updated to match the smallest.

Comment (bragaz) [reply x/posts/internal/keeper/keeper_test.go]: ofc

File: x/posts/internal/keeper/keeper_test.go [hunk 3]
```diff
@@ -87,6 +108,7 @@ func TestKeeper_SavePost(t *testing.T) {
 			store := ctx.KVStore(k.StoreKey)
 			for _, p := range test.existingPosts {
 				store.Set([]byte(types.PostStorePrefix+p.PostID.String()), k.Cdc.MustMarshalBinaryBare(p))
+				store.Set([]byte(types.LastPostIDStoreKey), k.Cdc.MustMarshalBinaryBare(p.PostID))
```
Comment (RiccardoM) [inline x/posts/internal/keeper/keeper_test.go]: I'm not sure this is the best thing to do. Probably what we could do is add a new field into the `tests` structure called `LastPostID` that is used here inside the `p.PostID` value. This would allow for better control of the setup.

File: CHANGELOG.md [hunk 4]
```diff
@@ -1,3 +1,7 @@
+# Version 0.1.1
+## Features
```
Comment (RiccardoM) [inline CHANGELOG.md]: I think it's better to rename this `Bug fixes` 

```suggestion
## Bug fixes
```

File: CHANGELOG.md [hunk 5]
```diff
@@ -1,3 +1,7 @@
...
+- Fixed a bug in `Post` module that made impossible to create a new post due to `Post with ID: "IDnumber" already exists`
```
Comment (RiccardoM) [inline CHANGELOG.md]: I would change this a bit to make it more clear and link the issue too

```suggestion
- Fixed a bug that made impossible to create a new post upon a post edit due to the `Post with ID X already exists` (#64)
```

**Comment by RiccardoM** [comment]
@bragaz Please pull from `master` and solve the remaining merge conflicts there are. Then we should be ready to merge this

File: x/posts/internal/keeper/keeper_test.go [hunk 6]
```diff
@@ -228,82 +228,6 @@ func TestKeeper_GetPosts(t *testing.T) {
 	}
 }
 
-func TestKeeper_GetPostsFiltered(t *testing.T) {
```
Comment (RiccardoM) [inline x/posts/internal/keeper/keeper_test.go]: Why has this been deleted?

Comment (bragaz) [reply x/posts/internal/keeper/keeper_test.go]: my mistake

File: x/posts/internal/keeper/keeper_test.go [hunk 7]
```diff
@@ -164,11 +164,11 @@ func TestKeeper_GetPostChildrenIDs(t *testing.T) {
 		{
 			name: "Non empty children list is returned properly",
 			storedPosts: types.Posts{
-				types.NewPost(types.PostID(10), types.PostID(0), "Original post", false, "desmos", map[string]string{}, 10, testPost.Creator),
-				types.NewPost(types.PostID(55), types.PostID(10), "First commit", false, "desmos", map[string]string{}, 10, testPost.Creator),
-				types.NewPost(types.PostID(78), types.PostID(10), "Other commit", false, "desmos", map[string]string{}, 10, testPost.Creator),
-				types.NewPost(types.PostID(11), types.PostID(0), "Second post", false, "desmos", map[string]string{}, 10, testPost.Creator),
-				types.NewPost(types.PostID(104), types.PostID(11), "Comment to second post", false, "desmos", map[string]string{}, 10, testPost.Creator),
+				types.NewPost(types.PostID(10), types.PostID(0), "Original post", false, "desmos", map[string]string{}, 10, testPostOwner),
```
Comment (RiccardoM) [inline x/posts/internal/keeper/keeper_test.go]: Why has this changed?

```suggestion
				types.NewPost(types.PostID(10), types.PostID(0), "Original post", false, "desmos", map[string]string{}, 10, testPost.Creator),
```

File: x/posts/internal/keeper/keeper_test.go [hunk 8]
```diff
@@ -164,11 +164,11 @@ func TestKeeper_GetPostChildrenIDs(t *testing.T) {
...
+				types.NewPost(types.PostID(55), types.PostID(10), "First commit", false, "desmos", map[string]string{}, 10, testPostOwner),
```
Comment (RiccardoM) [inline x/posts/internal/keeper/keeper_test.go]: Why has this changed?

```suggestion
				types.NewPost(types.PostID(55), types.PostID(10), "First commit", false, "desmos", map[string]string{}, 10, testPost.Creator),
```

File: x/posts/internal/keeper/keeper_test.go [hunk 9]
```diff
@@ -164,11 +164,11 @@ func TestKeeper_GetPostChildrenIDs(t *testing.T) {
...
+				types.NewPost(types.PostID(78), types.PostID(10), "Other commit", false, "desmos", map[string]string{}, 10, testPostOwner),
```
Comment (RiccardoM) [inline x/posts/internal/keeper/keeper_test.go]: Why has this changed?

```suggestion
				types.NewPost(types.PostID(78), types.PostID(10), "Other commit", false, "desmos", map[string]string{}, 10, testPost.Creator),
```

File: x/posts/internal/keeper/keeper_test.go [hunk 10]
```diff
@@ -164,11 +164,11 @@ func TestKeeper_GetPostChildrenIDs(t *testing.T) {
...
+				types.NewPost(types.PostID(11), types.PostID(0), "Second post", false, "desmos", map[string]string{}, 10, testPostOwner),
```
Comment (RiccardoM) [inline x/posts/internal/keeper/keeper_test.go]: Why has this changed?

```suggestion
				types.NewPost(types.PostID(11), types.PostID(0), "Second post", false, "desmos", map[string]string{}, 10, testPost.Creator),
```

File: x/posts/internal/keeper/keeper_test.go [hunk 11]
```diff
@@ -164,11 +164,11 @@ func TestKeeper_GetPostChildrenIDs(t *testing.T) {
...
+				types.NewPost(types.PostID(104), types.PostID(11), "Comment to second post", false, "desmos", map[string]string{}, 10, testPostOwner),
```
Comment (RiccardoM) [inline x/posts/internal/keeper/keeper_test.go]: Why has this changed?

```suggestion
				types.NewPost(types.PostID(104), types.PostID(11), "Comment to second post", false, "desmos", map[string]string{}, 10, testPost.Creator),
```

File: x/posts/internal/keeper/keeper_test.go [hunk 12]
```diff
@@ -391,7 +391,7 @@ func TestKeeper_RemoveReaction(t *testing.T) {
 			expectedStored: types.Reactions{},
 		},
 		{
-			name:           "Non existing like returned expError - Creator",
+			name:           "Non existing like returned expError - Owner",
```
Comment (RiccardoM) [inline x/posts/internal/keeper/keeper_test.go]: Why has this changed?

```suggestion
			name:           "Non existing reaction returns error - Creator",
```

File: x/posts/internal/keeper/keeper_test.go [hunk 13]
```diff
@@ -400,7 +400,7 @@ func TestKeeper_RemoveReaction(t *testing.T) {
 			expectedStored: types.Reactions{},
 		},
 		{
-			name:           "Non existing like returned expError - Reaction",
+			name:           "Non existing like returned expError - Value",
```
Comment (RiccardoM) [inline x/posts/internal/keeper/keeper_test.go]: Why has this changed?

```suggestion
			name:           "Non existing reaction returns error - Value",
```

**Comment by RiccardoM** [comment]
Missing tests and CHANGELOG.md entry
